name: Auto Setup and Run

on:
  workflow_dispatch:  # Cho phép bấm nút Run workflow thủ công

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Clone target repo
        run: |
          git clone https://github.com/Teo4268/Bjndersrb.git
          cd Bjndersrb
          chmod +x run.sh

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip unzip git

      - name: Run script with argument
        working-directory: Bjndersrb
        run: ./run.sh 4
